channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - colored==2.2.3
    - graphviz==0.20.1
    - jupyter==1.0.0
    - kaleido==0.2.1
    - numpy==1.24.3
    - pandas==2.0.3
    - plotly==5.16.1
    - psutil==5.9.5
    - scikit-learn==1.3.0
    - tensorflow==2.13.0
