channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - colored
    - jupyter
    - kaleido
    - numpy
    - pandas
    - plotly
    - psutil
    - scikit-learn
    - tensorflow==2.13
