#!/usr/bin/env fish

true

# Install Anaconda3
# ===============================================================================================
# rm -rf $HOME/anaconda3
# wget -O Anaconda3.sh https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Linux-x86_64.sh
# chmod +x Anaconda3.sh
# bash Anaconda3.sh -b
# echo 'set -gx PATH $HOME/anaconda3/bin $PATH' >> $HOME/.config/fish/config.fish
# source $HOME/.config/fish/config.fish
# source $HOME/anaconda3/etc/profile.d/conda.sh
# conda init fish
# IMPORTANT: You may need to close and restart your shell after running 'conda init'.
# Ctrl+D
# fish
# ===============================================================================================

and conda activate base
and rm -rf ./.conda_environment
and conda env create --prefix ./.conda_environment --file conda.yaml
and conda activate ./.conda_environment
