#!/usr/bin/env fish

true

and conda activate ./.conda_environment
and ipython3 decompose_games.py
and ipython3 train.py
and ipython3 play_against_random.py
and ipython3 stories.py


# RAY_memory_usage_threshold=1 ipython3 oracle.py
