#!/usr/bin/env fish

true

and conda activate ./.conda_environment
and source (ipython config.py | psub)
and env | grep OTHELLO
and ipython3 decompose_games.py
# and ipython3 train.py
# and ipython3 play_against_random.py
# and ipython3 stories.py

# and dot -Tsvg tree.dot -o tree.svg
